title: Gaudi's Garage
baseurl: /
permalink: /:title/
description: My projects and then some...
color_scheme: light
accent_color: violet
header:
  type: header
  title: Exto
  has_nav: true
  nav_links:
    - type: action
      label: Home
      url: /
      style: link
    - type: action
      label: Wearable Technology
      url: /wearable-technology/
      style: link
    - type: action
      label: Architecture
      url: /architecture/
      style: link
    - type: action
      label: Art
      url: /art/
      style: link
    - style: link
      new_window: false
      type: action
      url: /textile/
      label: Textile
    - type: action
      label: About
      url: /about/
      style: link
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: /posts/:title/
footer:
  type: footer
  content: "&copy; Stackbit-Exto. All rights reserved."
  links:
    - type: action
      label: Made with Stackbit.
      url: https://www.stackbit.com
      style: link
      new_window: true
  has_social: true
  social_links:
    - type: action
      label: Twitter
      url: https://twitter.com/
      style: icon
      icon_class: fa-twitter
      new_window: true
    - type: action
      label: Instagram
      url: https://www.instagram.com/
      style: icon
      icon_class: fa-instagram
      new_window: true
    - type: action
      label: Dribbble
      url: https://dribbble.com/
      style: icon
      icon_class: fa-dribbble
      new_window: true
    - type: action
      label: LinkedIn
      url: https://www.linkedin.com/
      style: icon
      icon_class: fa-linkedin
      new_window: true
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
